//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.ItniSlucai = new HashSet<ItniSlucai>();
            this.Operacii = new HashSet<Operacii>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string brTelefon { get; set; }
        public System.DateTime datumNaPriklucuvanje { get; set; }
        public string obrazovanie { get; set; }
        public string sertifikat { get; set; }
        public string jazici { get; set; }
        public int idBolnica { get; set; }
    
        public virtual Bolnica Bolnica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItniSlucai> ItniSlucai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacii> Operacii { get; set; }
    }
}
